package Nephia::Setup::View::Semantic;
use strict;
use warnings;
use Nephia::Setup;

{
    no strict qw/ subs refs /;
    no warnings qw/ redefine /;

    my $orig = *Nephia::Setup::create{CODE};
    *Nephia::Setup::create = sub {
        my ( $self, $appname ) = @_;
        $orig->( $self, $appname );
        my $approot = Nephia::Setup::approot( $appname );
        $approot->subdir( qw/ view injection / )->mkpath(1, 0755);
        $approot->file( qw/ view injection index.pl / )->spew('{ title => "title,h1" }');
    };

    *Nephia::Setup::psgi_file = sub {
        my ( $approot, $appname ) = @_;
        my $body = <<EOF;
use strict;
use warnings;
use FindBin;

use lib ("\$FindBin::Bin/lib", "\$FindBin::Bin/extlib/lib/perl5");
use $appname;
$appname->run( view => {
    class => 'Semantic',
});
EOF
        $approot->file( 'app.psgi' )->spew( $body );
    };


    *Nephia::Setup::index_template_file = sub {
        my $approot = shift;
        my $body = <<EOF;
<html>
<head>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  <link rel="stylesheet" href="/static/style.css" />
  <link rel="shortcut icon" href="/static/favicon.ico" />
  <title></title>
</head>
<body>
  <div class="title">
    <h1></h1>
  </div>
  <address class="generated-by">Generated by Nephia</address>
</body>
</html>
EOF
        $approot->file('view', 'index.html')->spew( $body );
    };


    *Nephia::Setup::app_class_file = sub {
        my ( $approot, $apppath, $appname ) = @_;
        my $name = $appname; $name =~ s/::/-/g;
        my $body = <<EOF;
package $appname;
use strict;
use warnings;
use Nephia;

our \$VERSION = 0.01;

path '/' => sub {
    my \$req = shift;
    return {
        template => [ 
            'index.html', 
            'injection/index.pl',
        ],
        title => '$name',
    };
};

1;
__END__

=head1 NAME

$appname - Web Application

=head1 SYNOPSIS

  \$ plackup

=head1 DESCRIPTION

$appname is web application based Nephia.

=head1 AUTHOR

clever guy

=head1 SEE ALSO

Nephia

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
EOF
        $approot->file( 'lib', @$apppath )->spew( $body );
    };

    *Nephia::Setup::makefile = sub {
        my ( $approot, $appname ) = @_;
        my $apppath = File::Spec->catfile( 'lib', split(/::/, $appname. '.pm') );
        my $body = <<EOF;
use inc::Module::Install;
all_from '$apppath';

requires 'Nephia' => 0.01;
requires 'Nephia::View::Semantic';

tests 't/*.t';

test_requires 'Test::More';

WriteAll;
EOF
        $approot->file('Makefile.PL')->spew( $body );
    };

}

1;

