package Nephia::Setup::View::Semantic;
use strict;
use warnings;
use parent qw( Nephia::Setup::Base );

sub create {
    my $self = shift;
    $self->SUPER::create;
    $self->injection_file;
}

sub injection_file {
    my $self = shift;
    $self->approot->subdir('view', 'injection')->mkpath(1, 0755);
    $self->approot->file('view', 'injection', 'index.pl')->spew('{ title => "title, h1" }');
}

sub psgi_file {
    my $self = shift;
    my $appname = $self->appname;
    my $body = <<EOF;
use strict;
use warnings;
use FindBin;

use lib ("\$FindBin::Bin/lib", "\$FindBin::Bin/extlib/lib/perl5");
use $appname;
$appname->run( view => { class => 'Semantic' } );
EOF
    $self->approot->file('app.psgi')->spew( $body );
}

sub app_class_file {
    my $self = shift;
    my $approot = $self->approot;
    my $appname = $self->appname;
    my $body = <<EOF;
package $appname;
use strict;
use warnings;
use Nephia;

our \$VERSION = 0.01;

path '/' => sub {
    my \$req = shift;
    return {
        template => [ 'index.html', 'injection/index.pl' ],
        title => '$appname',
    };
};

1;
__END__

=head1 NAME

$appname - Web Application

=head1 SYNOPSIS

  \$ plackup

=head1 DESCRIPTION

$appname is web application based Nephia.

=head1 AUTHOR

clever guy

=head1 SEE ALSO

Nephia

Nephia::View::Semantic

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
EOF
    $self->pmpath->dir->mkpath( 1, 0755 );
    $self->pmpath->spew( $body );
}

sub index_template_file {
    my $self = shift;
    my $body = <<EOF;
<html>
<head>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  <link rel="stylesheet" href="/static/style.css" />
  <link rel="shortcut icon" href="/static/favicon.ico" />
  <title></title>
</head>
<body>
  <div class="title">
    <h1></h1>
    <p>with Nephia::View::Semantic</p>
  </div>
  <address class="generated-by">Generated by Nephia</address>
</body>
</html>
EOF
    $self->approot->file('view', 'index.html')->spew( $body );
}

1;
